source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GOModules' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GOModules

  pod "SnapKit"
  pod "lottie-ios"
  pod "iCarousel"
  pod "SDWebImage"
  pod "SDWebImageWebPCoder"
  pod "Masonry"
  pod "JXCategoryView"
  pod "JXPagingView/Pager"
  pod "YYCategories"


end
